seed: 1234
load_path: "None"
#load_path: "/home/hin/school/nn/end/image-to-latex/model/epoch=1-val/loss=4.93-val/cer=0.91.ckpt"

trainer:
  gpus: 1
  overfit_batches: 0.0
  check_val_every_n_epoch: 2
  fast_dev_run: false
  max_epochs: 15
  min_epochs: 1
  num_sanity_val_steps: 0
  auto_lr_find: true
  checkpoint_callback: true

callbacks:
  model_checkpoint:
    save_top_k: 1
    save_weights_only: true
    mode: "min"
    monitor: "val/loss"
    filename: "{epoch}-{val/loss:.2f}-{val/cer:.2f}"
#    dirpath: "/home/hin/school/nn/end/image-to-latex/model"
  early_stopping:
    patience: 3
    mode: "min"
    monitor: "val/loss"
    min_delta: 0.001

data:
  batch_size: 32
  num_workers: 2
  pin_memory: false

lit_model:
  # Optimizer
  lr: 0.001
  weight_decay: 0.0001
  # Scheduler
  milestones: [10]
  gamma: 0.5
  # Model
  d_model: 128
  dim_feedforward: 256
  nhead: 4
  dropout: 0.3
  num_decoder_layers: 3
  max_output_len: 212

logger:
  project: "image-to-latex"
#  save_dir: "/home/hin/school/nn/end/image-to-latex/outputs"